"""Bcrypt to Werkzeug.security

Revision ID: ed344db43339
Revises: dc2cd5df2465
Create Date: 2022-03-17 10:52:38.587461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed344db43339'
down_revision = 'dc2cd5df2465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###
